### ISSUE TITLE
Failed to join server

### ISSUE THREAD

**Issue by diznover** [Elmartino4/high-level-enchants#11]
When I go to the server on which this mod is installed, I get this error 
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer high-level-enchants:crafting_special_cheap_books`

**Comment by Elmartino4** [comment]
Latest versions of the mod require it to be installed both client and server side

**Comment by diznover** [comment]
Thanks for the answer. 🥲
